config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dogs.apps import DogsConfig


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import CategoryListView, DogListView, DogCreateView, DogUpdateView, DogDeleteView, IndexView

app_name = DogsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('dogs/<int:pk>/', DogListView.as_view(), name='category_dogs'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/update/<int:pk>/', DogUpdateView.as_view(), name='dog_update'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

dogs/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='порода')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'


class Dog(models.Model):
    name = models.CharField(max_length=50, verbose_name='кличка')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='dogs/', verbose_name='фото', **NULLABLE)
    birth_day = models.DateField(**NULLABLE, verbose_name='дата рождения')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'

dogs/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from dogs.models import Category, Dog


# def index(request):
#     category_list = Category.objects.all()
#     context = {
#         'object_list': category_list[0:3],
#         'title': 'Питомник - Главное'
#     }
#     return render(request, 'dogs/index.html', context)

class IndexView(TemplateView):
    template_name = 'dogs/index.html'
    extra_context = {'title': 'Питомник - наши породы'}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data
# def categories(request):
#     category_list = Category.objects.all()
#     context = {
#         'object_list': category_list,
#         'title': 'Питомник - наши породы'
#     }
#     return render(request, 'dogs/categories.html', context)


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Питомник - наши породы'
    }


# def category_dogs(request,pk):
#     category_item = Category.objects.get(pk=pk)
#     dog_list = Dog.objects.filter(category_id=pk)
#     context = {
#         'object_list': dog_list,
#         'title': f'Собаки породы - {category_item.name}'
#     }
#     return render(request, 'dogs/dogs.html', context)

class DogListView(ListView):
    model = Dog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(id=self.kwargs.get('pk'))
        context_data['title'] = f'Собаки породы - {category_item.name}'
        return context_data


class DogCreateView(CreateView):
    model = Dog
    fields = ('name', 'category', 'photo', 'birth_day',)
    success_url = reverse_lazy('dogs:categories')


class DogUpdateView(UpdateView):
    model = Dog
    fields = ('name', 'category', 'photo', 'birth_day',)

    def get_success_url(self):
        return reverse('dogs:category_dogs', args=[self.object.category.pk])


class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('dogs:categories')

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/album.css'" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:categories' %}" class="text-white">Породы</a></li>
                        <li><a href="#" class="text-white">Like on Facebook</a></li>
                        <li><a href="#" class="text-white">Email me</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'dogs:index' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'dogs:index' %}">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/categories.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    {% include 'dogs/includes/inc_category.html' %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/category_list.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 mb-5">
        <a href="{% url 'dogs:dog_create' %}" class="btn btn-primary">Добавить собаку</a>
    </div>
    {% for object in object_list %}
    {% include 'dogs/includes/inc_category.html' %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dog_confirm_delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление собаки
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p> Действительно хотите удалить собаку {{ object.name }}</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warming" href="{% url 'dogs:category_dogs' object.category.pk %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/dog_form.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование собаки
                {% else %}
                Добавление собаки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Изменить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/dog_list.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.photo|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
                <p class="card-text">{{ object.birth_day}}</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-link" href="{% url 'dogs:dog_update' object.pk %}">Изменить</a>
                <a class="btn btn-danger float-right" href="{% url 'dogs:dog_delete' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.photo|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/includes/inc_category.html
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.name }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'dogs:category_dogs' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К собакам</a>
                </div>
            </div>
        </div>
    </div>
</div>

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_category.html' %}
    {% endfor %}
</div>
{% endblock %}